# Start your image with a node base image
FROM node:23-alpine

# The /app directory should act as the main application directory
WORKDIR /app/Backend/BlackJackNow

# Copy the app package and package-lock.json file
COPY ./Backend/BlackJackNow/package*.json ./
COPY ./Backend/BlackJackNow/tsconfig.json ./

# Copy local directories to the current local directory of our docker image (/app)
COPY ./Backend/BlackJackNow/src ./src
COPY ./Backend/BlackJackNow/test ./test
COPY ./Backend/BlackJackNow/jest.config.cjs ./

# Copy prisma schema
COPY ./Backend/BlackJackNow/prisma ./prisma

# Copy shared types
COPY ./Packages/shared-types/src ../../Packages/shared-types/src
COPY ./Packages/shared-types/package*.json ../../Packages/shared-types/
COPY ./Packages/shared-types/tsconfig.json ../../Packages/shared-types/

# Install node packages, install serve, build the app, and remove dependencies at the end
RUN npm run prepare:docker

EXPOSE 4003

# Start the app
CMD [ "npm", "run", "test" ]