services:
  backend:
    image: blackjacknow-backend:latest
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - '4000:4000'
    depends_on:
      - postgres
      - redis
      - firebase
    environment:
      PORT: 4000
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      NODE_ENV: ${NODE_ENV}
      FIREBASE_TYPE: ${FIREBASE_TYPE}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_PRIVATE_KEY_ID: ${FIREBASE_PRIVATE_KEY_ID}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      FIREBASE_CLIENT_ID: ${FIREBASE_CLIENT_ID}
      FIREBASE_AUTH_URI: ${FIREBASE_AUTH_URI}
      FIREBASE_TOKEN_URI: ${FIREBASE_TOKEN_URI}
      FIREBASE_AUTH_PROVIDER_X509_CERT_URL: ${FIREBASE_AUTH_PROVIDER_X509_CERT_URL}
      FIREBASE_CLIENT_X509_CERT_URL: ${FIREBASE_CLIENT_X509_CERT_URL}
      FIREBASE_UNIVERSE_DOMAIN: ${FIREBASE_UNIVERSE_DOMAIN}
      FIREBASE_AUTH_EMULATOR_HOST: ${FIREBASE_AUTH_EMULATOR_HOST}
      DISABLE_MIDDLEWARE: ${DISABLE_MIDDLEWARE}
    command: ['npm', 'run', 'dockercmd']
    container_name: backend
  queueWorker:
    image: blackjacknow-queue:latest
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      REDIS_URL: ${REDIS_URL}
    command: ['npm', 'run', 'dockercmd']
    container_name: queue-worker
  frontend:
    image: blackjacknow-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
        - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
        - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
        - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
        - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
        - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
        - VITE_FIREBASE_MEASUREMENT_ID=${VITE_FIREBASE_MEASUREMENT_ID}
        - VITE_NODE_ENV=${VITE_NODE_ENV}
        - VITE_FIREBASE_AUTH_EMULATOR_URL=${VITE_FIREBASE_AUTH_EMULATOR_URL}
        - VITE_SERVER_URL=${VITE_SERVER_URL}
    ports:
      - '8080:8080'
    depends_on:
      - backend
      - firebase
      - redis
      - postgres
    develop:
      watch:
        - action: sync+restart
          path: ./Frontend/BlackJackNow/src
          target: /app/Frontend/BlackJackNow/src
          ignore:
            - node_modules
            - dist
    command: ['npm', 'run', 'dev']
    container_name: frontend
  redis:
    image: redis/redis-stack:7.4.0-v2
    container_name: redis-stack
    ports:
      - '6379:6379' # Redis port
      - '8001:8001' # Redis Stack UI port
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:14.15-alpine3.21
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  firebase:
    image: firebase:latest
    container_name: firebase
    build:
      context: .
      dockerfile: Dockerfile.firebase
    ports:
      - '4001:4001'
      - '9099:9099'

volumes:
  redis_data:
  postgres_data:

